=== 00zhengfu00/cat/cat-core/src/main/resources/com/dianping/cat/configuration/model/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xs:element name="config" type="ConfigType"/>
<xs:complexType name="ConfigType">
<xs:sequence>
<xs:element name="app" type="AppType" minOccurs="0" maxOccurs="1"/>
<xs:element name="servers">
<xs:complexType>
<xs:sequence minOccurs="0" maxOccurs="unbounded">
<xs:element name="server" type="ServerType"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="bind" type="BindType" minOccurs="0" maxOccurs="1"/>
<xs:element name="filter" type="FilterType" minOccurs="0" maxOccurs="1"/>
<xs:element name="properties">
<xs:complexType>
<xs:sequence minOccurs="0" maxOccurs="unbounded">
<xs:element name="property" type="PropertyType"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="mode" type="xs:string" use="required"/>
<xs:attribute name="base-log-dir" type="xs:string" default="target/catlog"/>
<xs:attribute name="base-log-url" type="xs:string"/>
</xs:complexType>
<xs:complexType name="AppType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="domain" type="xs:string" use="required"/>
<xs:attribute name="ip" type="xs:string"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
<xs:complexType name="ServerType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="ip" type="xs:string"/>
<xs:attribute name="port" type="xs:int" default="2280"/>
<xs:attribute name="enabled" type="xs:boolean" default="true"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
<xs:complexType name="BindType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="ip" type="xs:string"/>
<xs:attribute name="port" type="xs:int" default="2280"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
<xs:complexType name="FilterType">
<xs:sequence>
<xs:element name="domain" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="PropertyType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="name" type="xs:string" use="required"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:schema>

=== 00zhengfu00/cat/cat-core/src/test/resources/com/dianping/cat/message/configuration/model/server.xml
<config mode="server" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
	<bind ip="192.168.8.21" />
	<filter>
		<domain>Review</domain>
		<domain>Group</domain>
	</filter>
	<properties>
		<property name="failure-base-dir">/data/appdatas/cat/report/failure/</property>
		<property name="transaction-base-dir">/data/appdatas/cat/report/transaction/</property>
	</properties>
</config>

=== 00zhengfu00/cat/cat-core/src/test/resources/com/dianping/cat/message/configuration/config.xml
<config mode="client" enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
   <servers>
      <server ip="192.168.8.21" port="2280" enabled="true"/>
      <server ip="192.168.8.22" port="2281" enabled="false"/>
      <server ip="192.168.8.23" port="2280" enabled="true"/>
   </servers>
   <domain id="Group" enabled="true"/>
   <domain id="Review" ip="192.168.8.1" enabled="false"/>
   <bind ip="192.168.8.21" port="2280"/>
   <properties>
      <property name="failure-base-dir">/data/appdatas/cat/report/failure/</property>
      <property name="transaction-base-dir">/data/appdatas/cat/report/transaction/</property>
   </properties>
   <base-log-dir>target/catlog</base-log-dir>
</config>
